baseURL: 'https://blog.kvd.ink/'
languageCode: 'zh-CN'
defaultContentLanguage: cn
hasCJKLanguage: true
title: onexen
theme: hugo-book
menu:
  before:
    - identifier: posts
      name: Posts
      url: /posts
    - identifier: about
      name: About
      url: /about
    - identifier: email
      name: Send Email
      url: mailto:KaivnD@hotmail.com
    - identifier: github
      name: Github
      url: https://github.com/KaivnD/blog
disablePathToLower: true
enableGitInfo: true
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 4
  highlight:
    style: monokai
params:
  BookTheme: 'auto'
  BookSearch: true
